### ISSUE TITLE
Fix Logging error

### ISSUE THREAD

**Issue by Trippik** [Trippik/Docker-Volume-Backup-Tool#6]
--- Logging error ---

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit

    msg = self.format(record)

          ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format

    return fmt.format(record)

           ^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format

    record.message = record.getMessage()

                     ^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage

    msg = msg % self.args

          ~~~~^~~~~~~~~~~

TypeError: not all arguments converted during string formatting

Call stack:

  File "/usr/local/bin/Docker-Volume-Backup-Tool", line 33, in <module>

    sys.exit(load_entry_point('Docker-Volume-Backup-Tool==1.0', 'console_scripts', 'Docker-Volume-Backup-Tool')())

  File "/usr/local/lib/python3.11/site-packages/Docker_Volume_Backup_Tool-1.0-py3.11.egg/docker_volume_backup/app.py", line 47, in main

    job.run()

  File "/usr/local/lib/python3.11/site-packages/Docker_Volume_Backup_Tool-1.0-py3.11.egg/docker_volume_backup/lib/job.py", line 93, in run

    self.save_file_s3(s3_client)

  File "/usr/local/lib/python3.11/site-packages/Docker_Volume_Backup_Tool-1.0-py3.11.egg/docker_volume_backup/lib/job.py", line 46, in save_file_s3

    logging.info("Starting upload of {}", self.filename)

Message: 'Starting upload of {}'

**Comment by Trippik** [comment]
Fixed in 4.0.2 release https://github.com/Trippik/Docker-Volume-Backup-Tool/releases/tag/4.0.2
